### ISSUE TITLE
Use relative values as input parameters for flexible loads

### ISSUE THREAD

**Issue by matteorossini** [Electa-Git/FlexPlan.jl#104]
### Background

The parameters related to the _power_ of flexible loads (`p_red_max`, `p_shift_up_max`, and `p_shift_down_max`) use relative values: they are expressed as a fraction of the reference power demand.

Those related to _energy_ (`e_nce_max` and `p_shift_down_tot_max`), on the other hand, use absolute values: they are expressed in MWh.

### Problem

Expressing the parameters related to the _energy_ of flexible loads as absolute values has some disadvantages:

- Their understanding is not immediate. To assess the magnitude of a value for a particular load, it is necessary to consider the reference power demand, the length of the time horizon, and figure out the average value of the timeseries for that load.
- They are independent of the time horizon. Thus, if one wants to change the duration of the time horizon, they have to rescale these parameters to obtain a similar effect.
- They are inconsistent with `p_red_max`, `p_shift_up_max`, and `p_shift_down_max`.

### Possible solution

`e_nce_max` and `p_shift_down_tot_max` could alternatively be expressed as relative values, i.e. as a fraction of the total reference energy demand (the sum of the reference power demand over the time horizon, multiplied by `time_elapsed` to convert the resulting power to an energy). This [has already been proposed](https://github.com/Electa-Git/FlexPlan.jl/issues/66#issuecomment-824085165), but not yet applied.

**Comment by hakanergun** [comment]
Indeed, this makes sense, it is much more consistent that way.

**Comment by matteorossini** [comment]
Fixed in `develop` branch. Will be merged in `master` branch with the next release.
