### ISSUE TITLE
Avoid requiring flexible load parameters for those loads that are not flexible

### ISSUE THREAD

**Issue by matteorossini** [Electa-Git/FlexPlan.jl#105]
### Background

Currently, in ([stochastic](https://github.com/Electa-Git/FlexPlan.jl/blob/a2acae39b08878ca1c5383118c1068b3258dcaf0/src/prob/stochastic_flexible_tnep.jl)) [flexible TNEP](https://github.com/Electa-Git/FlexPlan.jl/blob/a2acae39b08878ca1c5383118c1068b3258dcaf0/src/prob/flexible_tnep.jl) problems two types of loads are supported:

1. fixed loads (`flex == 0`): they absorb their reference demand, unless involuntary curtailment is applied, in which case their absorption is reduced accordingly.
2. flexible loads (`flex == 1`): their behavior depends on the value of the activation variable `:z_flex`. If `:z_flex == 0`, they act as fixed loads (previous case); if `:z_flex == 1`, instead, they also support energy reduction and demand shifting.

### Problems

- `p_red_max`, `e_nce_max`, `p_shift_down_max`,`p_shift_up_max`, and `p_shift_down_tot_max` input parameters are required for fixed loads even if they should not be used at all.
For example, `p_red_max` is required because it is used in [`variable_demand_reduction`](https://github.com/Electa-Git/FlexPlan.jl/blob/a2acae39b08878ca1c5383118c1068b3258dcaf0/src/core/flexible_demand.jl#L48-L60) which is defined for each load, regardless of the value of `flex`.

- `:p_nce`, `:ence`, `:pshift_up`, `:pshift_down`, `:pshift_up_tot`, `:pshift_down_tot`, `:z_flex`, and `:z_flex_investment` are defined for fixed loads too (and their value is forced to be 0 in [`constraint_fixed_demand`](https://github.com/Electa-Git/FlexPlan.jl/blob/a2acae39b08878ca1c5383118c1068b3258dcaf0/src/core/flexible_demand.jl#L290-L306)), even if they could be avoided.

### Possible solution

The variables related to flexible loads only should be defined over the flexible loads, rather than over every load. A good way to do this would be: first, define a `:flex_load` Dict of flexible loads in each nw's `ref` through a [model reference](https://github.com/Electa-Git/FlexPlan.jl/blob/a2acae39b08878ca1c5383118c1068b3258dcaf0/src/core/model_references.jl), then change the definition of the aforementioned variables to use `:flex_load` instead of `:load`.

**Comment by hakanergun** [comment]
Indeed. I think that this is really an artefact from the very first implementation of the demand model, where we didn't want to spend a lot of time in the data processing, considering the small test cases. But indeed, this would be a nice enhancement.

**Comment by matteorossini** [comment]
Fixed in `develop` branch. Will be merged in `master` branch with the next release.
