### ISSUE TITLE
Rename flexible load parameters/variables

### ISSUE THREAD

**Issue by matteorossini** [Electa-Git/FlexPlan.jl#106]
An overall renaming of the flexible loads parameters/variables could be considered.

For instance, `p_shift_down_tot_max` despite its name is related to an energy (not a power) and is also a bound for the upward demand shifting (not just the downward demand shifting). Some renaming [has already been proposed](https://github.com/Electa-Git/FlexPlan.jl/issues/66#issuecomment-824085165), but not yet applied.

Performing a rename is not a tough task (it boils down to some find/replace). I can make a proposal for discussion here.

However, since the parameter names appear in every input file, this is a delicate matter. Before I begin I want to gather some opinion on whether such a renaming is appropriate, or whether it is better to stick to the current parameter names so as not to modify input files and any other code that relies on FlexPlan.jl.

**Comment by hakanergun** [comment]
Indeed, I am in favour of replacing such names as it only creates confusion, especially while the documentation is not very extensive. W.r.t. the test files, see also #89  and #96 . I think that a general clean up is needed here.

**Comment by matteorossini** [comment]
Here is my proposal.


### Decision variables

| Current name        | Proposal    |
| :------------------- | :----------- |
| z_flex *            |             |
| z_flex_investment * |             |
| pflex               |             |
| qflex               |             |
| pcurt               |             |
| pnce *              | pnc         |
| ence *              | enc         |
| pshift_up *         |             |
| pshift_up_tot *     | eshift_up   |
| pshift_down *       |             |
| pshift_down_tot *   | eshift_down |

*: only used for flexible loads.


### Solution keys

| Current name    | Proposal    |
| :--------------- | :----------- |
| isflex          | flex        |
| investment      |             |
| pflex           |             |
| qflex           |             |
| pcurt           |             |
| pnce            | pnc         |
| ence            | enc         |
| pshift_up       |             |
| pshift_up_tot   | eshift_up   |
| pshift_down     |             |
| pshift_down_tot | eshift_down |


### Parameters

| Current name(s)                    | Proposal        |
| :---------------------------------- | :--------------- |
| flex                               |                 |
| pd                                 |                 |
| ed_tot ***                         | ed              |
| qd                                 |                 |
| pf_angle                           |                 |
| p_red_max *                        | pnc_max         |
| e_nce_max *                        | enc_max         |
| p_shift_up_max *                   | pshift_up_max   |
| p_shift_down_max *                 | pshift_down_max |
| t_grace_up *                       | tshift_up       |
| t_grace_down *                     | tshift_down     |
| p_shift_down_tot_max *             | eshift_max      |
| cost_curt * \| cost_curtailment ** | cost_curt       |
| cost_reduction *                   | cost_nc         |
| cost_shift_up *                    |                 |
| cost_shift_down *                  |                 |
| cost_inv * \| cost_investment **   | cost_inv        |
| co2_cost *                         |                 |
| lifetime *                         |                 |

*: input parameter only required for flexible loads

**: model parameter, different name w.r.t. input parameter

***: model parameter, computed during model instantiation



## Questions and alternatives

When it comes to names it becomes a matter of personal preference, nevertheless I think that we should strive to find the most immediate terms. Here are some possible naming alternatives that came to my mind.

- Variables starting with `e` are _accumulated energies_: in a multinetwork, only those relating to the last period contain the total energy. Should we add `_acc` (or something similar) at the end to stress this concept?
- Parameters ending with `_max` are _adimensional values_: they are fractions relative to the reference power demand (or reference energy demand). Would we better use something like `_rel_max` as a suffix?
- Variable and parameters relating to the power (or energy) _not consumed_ contain the abbreviation `nc`. The term _voluntary reduction_ could be used instead and we could substitute `nc` with `red`. Which is more clear?

**Comment by ibsperstad** [comment]
This looks great, and I have no objections to your suggestions. As you write in your comments, names become a matter of preference and there are no obviously correct solutions. Here are my brief comments to your bullet points:
- Leaving out "_acc" for the energy measures should be ok since I regard it as implied that energy quantities are accumulated. 
- It would be good to be able to keep in mind that "_max" parameters are relative and not absolute values. Perhaps using "_max_rel" or "_rel_max" would be helpful if it does not make the names too long(?)
- I am myself most used to calling it "voluntary load reduction" (or "red" in brief), but "power not consumed" is by now also a fairly established term in the FlexPlan documentation.

**Comment by matteorossini** [comment]
Thanks @ibsperstad, I just updated the proposal with both `_max` --> `_rel_max` and `nc` --> `red` changes. As for the voluntary reduction, I had only checked FlexPlan D1.2 and found both the terms _energy not consumed_ and _voluntary reduction_, but later noticed that D2.1 only uses the latter.

I will soon prepare a PR that implements the renaming.

**Comment by matteorossini** [comment]
Fixed in `develop` branch. Will be merged in `master` branch with the next release.
