### ISSUE TITLE
Candidate storage devices are built even if not needed

### ISSUE THREAD

**Issue by matteorossini** [Electa-Git/FlexPlan.jl#122]
If the energy required at the time horizon boundaries is positive, then candidate storage devices are built, even if they are not needed:

```julia
import FlexPlan; const _FP = FlexPlan
import JuMP
import Cbc
using Test

cbc = JuMP.optimizer_with_attributes(Cbc.Optimizer, "logLevel" => 0)
data = _FP.parse_file(normpath(dirname(pathof(FlexPlan)),"../test/data/case2/case2_d_strg.m"))
_FP.add_dimension!(data, :hour, 4)
_FP.add_dimension!(data, :year, 1; metadata = Dict{String,Any}("scale_factor"=>1))
loadprofile = collect(reshape(range(0,1.1005;length=4),:,1)) # Create a load profile: ramp from 0 to 1.1005 times the rated value of load
time_series = _FP.make_time_series(data; loadprofile)
mn_data = _FP.make_multinetwork(data, time_series)
result = _FP.flex_tnep(mn_data, _FP.BFARadPowerModel, cbc)

@test result["solution"]["nw"]["1"]["ne_storage"]["1"]["isbuilt"] ≈ 0.0 atol=1e-3
```

**Comment by hakanergun** [comment]
even if I think that it is not strictly necessary, using:

` JuMP.@constraint(pm.model, se >= energy * _PM.var(pm, n_2, :z_strg_ne, i))` instead of ` JuMP.@constraint(pm.model, se >= energy)`. That would put the lower bound to zero, still remaining linear. 

https://github.com/Electa-Git/FlexPlan.jl/blob/f2cc7ec32b523a7c62802f576a07b780479eb804/src/core/storage.jl#L491

**Comment by matteorossini** [comment]
Great catch!

It seems we also need to change `(1-self_discharge_rate)^time_elapsed)*energy` to `(1-self_discharge_rate)^time_elapsed)*energy*z` in the initial energy constraint:
https://github.com/Electa-Git/FlexPlan.jl/blob/f2cc7ec32b523a7c62802f576a07b780479eb804/src/core/storage.jl#L457-L464

**Comment by hakanergun** [comment]
Should be fixed in the last release.
